/**
 * @syntherium/contracts
 * 
 * Generated TypeScript types from OpenAPI specification.
 * 
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Run `pnpm api:sync` to regenerate from OpenAPI specs.
 */

// This file will be replaced by generated types
// Placeholder export to allow initial build
export type Placeholder = 'GENERATED_TYPES_GO_HERE';

// After running api:sync, this will export types like:
// export type * from './api-types';
